name: Zbuduj Android 16KB
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      - name: Znajdz foldery i napraw bledy autorow
        run: |
          # Szukamy głównego pliku Android.mk w projekcie
          MAIN_ANDROID_MK=$(find . -name "Android.mk" | awk '{ print length($0), $0 }' | sort -n | cut -d ' ' -f2- | head -n 1)
          
          JNI_DIR=$(dirname "$MAIN_ANDROID_MK")
          PROJECT_DIR=$(dirname "$JNI_DIR")
          
          echo "Znaleziono folder JNI w: $JNI_DIR"
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          
          # Konfiguracja 16KB i architektur
          echo "APP_LDFLAGS += -Wl,-z,max-page-size=16384" >> "$JNI_DIR/Application.mk"
          echo "APP_ABI := arm64-v8a armeabi-v7a x86_64 x86" >> "$JNI_DIR/Application.mk"
          echo "APP_PLATFORM := android-21" >> "$JNI_DIR/Application.mk"
          echo "APP_ALLOW_MISSING_DEPS := true" >> "$JNI_DIR/Application.mk"

          # Chirurgiczne cięcie brakujących modułów (które psuły poprzednio kompilację)
          sed -i '/freetype/d' "$JNI_DIR/Android.mk"
          sed -i '/tiff/d' "$JNI_DIR/Android.mk"
          sed -i '/gif/d' "$JNI_DIR/Android.mk"
          
          # ----- NOWY KROK NAPRAWCZY -----
          # Szukamy absolutnej ścieżki do folderu zawierającego plik sqlite3.h
          SQLITE_DIR=$(dirname "$(find $(pwd) -name 'sqlite3.h' | head -n 1)")
          echo "Znaleziono baze w folderze: $SQLITE_DIR"
          
          # Mówimy kompilatorowi, żeby tam zaglądał (Flaga -I)
          echo "APP_CFLAGS += -I$SQLITE_DIR" >> "$JNI_DIR/Application.mk"
          echo "APP_CXXFLAGS += -I$SQLITE_DIR" >> "$JNI_DIR/Application.mk"

      - name: Przygotowanie Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c

      - name: Kompilacja biblioteki
        run: $ANDROID_NDK_HOME/ndk-build -C ${{ env.PROJECT_DIR }} APP_ALLOW_MISSING_DEPS=true

      - name: Zapisywanie gotowych plików
        uses: actions/upload-artifact@v4
        with:
          name: gotowe-biblioteki-16kb
          path: ${{ env.PROJECT_DIR }}/libs/
