name: Zbuduj Android 16KB
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie kodu
        uses: actions/checkout@v4

      - name: Znajdz foldery i zastosuj ostateczna naprawe naglowkow
        run: |
          # Szukamy głównego pliku Android.mk w projekcie
          MAIN_ANDROID_MK=$(find . -name "Android.mk" | awk '{ print length($0), $0 }' | sort -n | cut -d ' ' -f2- | head -n 1)
          
          JNI_DIR=$(dirname "$MAIN_ANDROID_MK")
          PROJECT_DIR=$(dirname "$JNI_DIR")
          
          echo "Znaleziono folder JNI w: $JNI_DIR"
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          
          # Konfiguracja 16KB i architektur
          echo "APP_LDFLAGS += -Wl,-z,max-page-size=16384" >> "$JNI_DIR/Application.mk"
          echo "APP_ABI := arm64-v8a armeabi-v7a x86_64 x86" >> "$JNI_DIR/Application.mk"
          echo "APP_PLATFORM := android-21" >> "$JNI_DIR/Application.mk"
          echo "APP_ALLOW_MISSING_DEPS := true" >> "$JNI_DIR/Application.mk"

          # Chirurgiczne cięcie brakujących modułów
          sed -i '/freetype/d' "$JNI_DIR/Android.mk"
          sed -i '/tiff/d' "$JNI_DIR/Android.mk"
          sed -i '/gif/d' "$JNI_DIR/Android.mk"
          
          # Naprawa błędu ilości argumentów dla RasterLite2
          sed -i 's/,p_rl2_data,0/,0/g' "$JNI_DIR/javasqlite-20120209/native/sqlite_jni.c"
          
          # ----- OSTATECZNA BROŃ (SNAJPER - ABSOLUTNE ŚCIEŻKI) -----
          SQLITE_INC=$(dirname "$(find $(pwd) -name 'sqlite3.h' | head -n 1)")
          SPATIALITE_PRIV_INC=$(dirname "$(find $(pwd) -name 'spatialite_private.h' | head -n 1)")
          SPATIALITE_PUB_INC=$(dirname "$(find $(pwd) -name 'spatialite.h' | head -n 1)")
          
          # Kod żąda "rasterlite2/rasterlite2.h", więc musimy podać folder O JEDEN POZIOM WYŻEJ
          RL2_FILE=$(find $(pwd) -name 'rasterlite2.h' | head -n 1)
          RL2_INC=$(dirname $(dirname "$RL2_FILE"))
          
          # Dodajemy te absolutne ścieżki
          echo "APP_CFLAGS += -I$SQLITE_INC -I$SPATIALITE_PRIV_INC -I$SPATIALITE_PUB_INC -I$RL2_INC" >> "$JNI_DIR/Application.mk"
          echo "APP_CXXFLAGS += -I$SQLITE_INC -I$SPATIALITE_PRIV_INC -I$SPATIALITE_PUB_INC -I$RL2_INC" >> "$JNI_DIR/Application.mk"

          # ----- WYŁĄCZENIE RESTRYKCJI NOWEGO KOMPILATORA -----
          echo "APP_CFLAGS += -Wno-implicit-function-declaration -Wno-int-conversion -Wno-incompatible-pointer-types" >> "$JNI_DIR/Application.mk"

      - name: Przygotowanie Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c

      - name: Kompilacja biblioteki
        run: $ANDROID_NDK_HOME/ndk-build -C ${{ env.PROJECT_DIR }} APP_ALLOW_MISSING_DEPS=true

      - name: Zapisywanie gotowych plików
        uses: actions/upload-artifact@v4
        with:
          name: gotowe-biblioteki-16kb
          path: ${{ env.PROJECT_DIR }}/libs/
